import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const Playfair = Playfair_Display({
  variable: "--font-Playfair", 
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className={`${geistSans.variable} ${geistMono.variable} ${Playfair.variable} h-full antialiased overflow-x-hidden`}
    >
      {/* overflow-x-hidden: red de seguridad global para elementos decorativos
          (como el brillo de Biografía) que se desbordan intencionalmente de su
          contenedor. Si llegan a tocar el borde real de la pantalla, se recortan
          ahí (invisible), en vez de necesitar un overflow-hidden ajustado en
          cada componente por separado. */}
      <body className="min-h-full flex flex-col overflow-x-hidden">{children}</body>
    </html>
  );
}